  
dist: trusty
language: java
jdk:
 - oraclejdk13

addons:
 sonarcloud:
  organization: "fra199889"
  token:
   secure: "28e6288d82b0540e2db1e6364c8109a468e8939c"

script: 

- ant build
- sonar-scanner



















